[package]
name = "alexandria_storage"
version.workspace = true
description = "Starknet storage utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/storage"
edition = "2023_11"
cairo-version = "2.12.1"

[tool]
fmt.workspace = true

[dependencies]
starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true