[package]
name = "alexandria_math"
version.workspace = true
description = "A set of math libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/math"
edition = "2023_11"
cairo-version = "2.12.2"

experimental-features = ["user_defined_inline_macros"]

[tool]
fmt.workspace = true

[dev-dependencies]
snforge_std.workspace = true
