[workspace]
members = [
  "packages/data_structures",
  "packages/encoding",
  "packages/linalg",
  "packages/macros",
  "packages/macros_tests",
  "packages/math",
  "packages/merkle_tree",
  "packages/numeric",
  "packages/json",
  "packages/searching",
  "packages/sorting",
  "packages/storage",
  "packages/ascii",
  "packages/bytes",
  "packages/utils",
  "packages/evm",
  "packages/btc",
]
name = "alexandria"
version = "0.6.2"

description = "Community maintained Cairo and Starknet libraries"
homepage = "https://github.com/keep-starknet-strange/alexandria/"
cairo-version = "2.13.1"

[workspace.dependencies]
starknet = "2.13.1"
cairo_test = "2.13.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.51.1" }

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.package]
version = "0.6.2"

[profile.coverage]
sierra = true

[scripts]
all = "scarb build && snforge test"
