[workspace]
members = [
  "packages/data_structures",
  "packages/encoding",
  "packages/linalg",
  "packages/macros",
  "packages/macros_tests",
  "packages/math",
  "packages/merkle_tree",
  "packages/numeric",
  "packages/json",
  "packages/searching",
  "packages/sorting",
  "packages/storage",
  "packages/ascii",
  "packages/bytes",
  "packages/utils",
  "packages/evm",
  "packages/btc",
]
name = "alexandria"
version = "0.6.0"

description = "Community maintained Cairo and Starknet libraries"
homepage = "https://github.com/keep-starknet-strange/alexandria/"
cairo-version = "2.12.1"

[workspace.dependencies]
starknet = "2.12.1"
cairo_test = "2.12.1"

[workspace.tool.fmt]
sort-module-level-items = true

[workspace.package]
version = "0.6.0"

[scripts]
all = "scarb build && scarb test"
