use alexandria_math::sha256;
use snforge_std::*;

#[test]
fn sha256_empty_test() {
    let mut input: Array<u8> = array![];
    let result = sha256::sha256(input);

    // result should be 0xE3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    assert(result.len() == 32, 'assertion failed');
    assert(*result[0] == 0xE3, 'assertion failed');
    assert(*result[1] == 0xB0, 'assertion failed');
    assert(*result[2] == 0xC4, 'assertion failed');
    assert(*result[3] == 0x42, 'assertion failed');
    assert(*result[4] == 0x98, 'assertion failed');
    assert(*result[5] == 0xFC, 'assertion failed');
    assert(*result[6] == 0x1C, 'assertion failed');
    assert(*result[7] == 0x14, 'assertion failed');
    assert(*result[8] == 0x9A, 'assertion failed');
    assert(*result[9] == 0xFB, 'assertion failed');
    assert(*result[10] == 0xF4, 'assertion failed');
    assert(*result[11] == 0xC8, 'assertion failed');
    assert(*result[12] == 0x99, 'assertion failed');
    assert(*result[13] == 0x6F, 'assertion failed');
    assert(*result[14] == 0xB9, 'assertion failed');
    assert(*result[15] == 0x24, 'assertion failed');
    assert(*result[16] == 0x27, 'assertion failed');
    assert(*result[17] == 0xAE, 'assertion failed');
    assert(*result[18] == 0x41, 'assertion failed');
    assert(*result[19] == 0xE4, 'assertion failed');
    assert(*result[20] == 0x64, 'assertion failed');
    assert(*result[21] == 0x9B, 'assertion failed');
    assert(*result[22] == 0x93, 'assertion failed');
    assert(*result[23] == 0x4C, 'assertion failed');
    assert(*result[24] == 0xA4, 'assertion failed');
    assert(*result[25] == 0x95, 'assertion failed');
    assert(*result[26] == 0x99, 'assertion failed');
    assert(*result[27] == 0x1B, 'assertion failed');
    assert(*result[28] == 0x78, 'assertion failed');
    assert(*result[29] == 0x52, 'assertion failed');
    assert(*result[30] == 0xB8, 'assertion failed');
    assert(*result[31] == 0x55, 'assertion failed');
}

#[test]
fn sha256_random_data_test() {
    let mut input: Array<u8> = array![
        0x57, 0x77, 0x71, 0x71, 0x66, 0x50, 0x45, 0x51, 0x51, 0x43, 0x39, 0x48, 0x38,
    ];
    let result = sha256::sha256(input);
    assert(*result[0] == 61, 'assertion failed');
    assert(*result[1] == 226, 'assertion failed');
    assert(*result[2] == 188, 'assertion failed');
    assert(*result[3] == 242, 'assertion failed');
    assert(*result[4] == 118, 'assertion failed');
    assert(*result[5] == 121, 'assertion failed');
    assert(*result[6] == 7, 'assertion failed');
    assert(*result[7] == 225, 'assertion failed');
    assert(*result[8] == 150, 'assertion failed');
    assert(*result[9] == 220, 'assertion failed');
    assert(*result[10] == 105, 'assertion failed');
    assert(*result[11] == 158, 'assertion failed');
    assert(*result[12] == 185, 'assertion failed');
    assert(*result[13] == 180, 'assertion failed');
    assert(*result[14] == 139, 'assertion failed');
    assert(*result[15] == 103, 'assertion failed');
    assert(*result[16] == 221, 'assertion failed');
    assert(*result[17] == 95, 'assertion failed');
    assert(*result[18] == 56, 'assertion failed');
    assert(*result[19] == 88, 'assertion failed');
    assert(*result[20] == 209, 'assertion failed');
    assert(*result[21] == 159, 'assertion failed');
    assert(*result[22] == 255, 'assertion failed');
    assert(*result[23] == 247, 'assertion failed');
    assert(*result[24] == 145, 'assertion failed');
    assert(*result[25] == 146, 'assertion failed');
    assert(*result[26] == 83, 'assertion failed');
    assert(*result[27] == 110, 'assertion failed');
    assert(*result[28] == 185, 'assertion failed');
    assert(*result[29] == 5, 'assertion failed');
    assert(*result[30] == 248, 'assertion failed');
    assert(*result[31] == 15, 'assertion failed');
}

#[test]
fn sha256_lorem_ipsum_test() {
    // Lorem ipsum, or lsipsum as it is sometimes known, is dummy text used in laying out print,
    // graphic or web designs.
    // The passage is attributed to an unknown typesetter in the 15th century who is thought to have
    // scrambled parts of Cicero's De Finibus Bonorum et Malorum for use in a type specimen book. It
    // usually begins with
    let mut input = array![];
    input.append('L');
    input.append('o');
    input.append('r');
    input.append('e');
    input.append('m');
    input.append(' ');
    input.append(0x69);
    input.append(0x70);
    input.append(0x73);
    input.append(0x75);
    input.append(0x6D);
    input.append(0x2C);
    input.append(0x20);
    input.append(0x6F);
    input.append(0x72);
    input.append(0x20);
    input.append(0x6C);
    input.append(0x73);
    input.append(0x69);
    input.append(0x70);
    input.append(0x73);
    input.append(0x75);
    input.append(0x6D);
    input.append(0x20);
    input.append(0x61);
    input.append(0x73);
    input.append(0x20);
    input.append(0x69);
    input.append(0x74);
    input.append(0x20);
    input.append(0x69);
    input.append(0x73);
    input.append(0x20);
    input.append(0x73);
    input.append(0x6F);
    input.append(0x6D);
    input.append(0x65);
    input.append(0x74);
    input.append(0x69);
    input.append(0x6D);
    input.append(0x65);
    input.append(0x73);
    input.append(0x20);
    input.append(0x6B);
    input.append(0x6E);
    input.append(0x6F);
    input.append(0x77);
    input.append(0x6E);
    input.append(0x2C);
    input.append(0x20);
    input.append(0x69);
    input.append(0x73);
    input.append(0x20);
    input.append(0x64);
    input.append(0x75);
    input.append(0x6D);
    input.append(0x6D);
    input.append(0x79);
    input.append(0x20);
    input.append(0x74);
    input.append(0x65);
    input.append(0x78);
    input.append(0x74);
    input.append(0x20);
    input.append(0x75);
    input.append(0x73);
    input.append(0x65);
    input.append(0x64);
    input.append(0x20);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x6C);
    input.append(0x61);
    input.append(0x79);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x67);
    input.append(0x20);
    input.append(0x6F);
    input.append(0x75);
    input.append(0x74);
    input.append(0x20);
    input.append(0x70);
    input.append(0x72);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x74);
    input.append(0x2C);
    input.append(0x20);
    input.append(0x67);
    input.append(0x72);
    input.append(0x61);
    input.append(0x70);
    input.append(0x68);
    input.append(0x69);
    input.append(0x63);
    input.append(0x20);
    input.append(0x6F);
    input.append(0x72);
    input.append(0x20);
    input.append(0x77);
    input.append(0x65);
    input.append(0x62);
    input.append(0x20);
    input.append(0x64);
    input.append(0x65);
    input.append(0x73);
    input.append(0x69);
    input.append(0x67);
    input.append(0x6E);
    input.append(0x73);
    input.append(0x2E);
    input.append(0x20);
    input.append(0x54);
    input.append(0x68);
    input.append(0x65);
    input.append(0x20);
    input.append(0x70);
    input.append(0x61);
    input.append(0x73);
    input.append(0x73);
    input.append(0x61);
    input.append(0x67);
    input.append(0x65);
    input.append(0x20);
    input.append(0x69);
    input.append(0x73);
    input.append(0x20);
    input.append(0x61);
    input.append(0x74);
    input.append(0x74);
    input.append(0x72);
    input.append(0x69);
    input.append(0x62);
    input.append(0x75);
    input.append(0x74);
    input.append(0x65);
    input.append(0x64);
    input.append(0x20);
    input.append(0x74);
    input.append(0x6F);
    input.append(0x20);
    input.append(0x61);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x75);
    input.append(0x6E);
    input.append(0x6B);
    input.append(0x6E);
    input.append(0x6F);
    input.append(0x77);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x74);
    input.append(0x79);
    input.append(0x70);
    input.append(0x65);
    input.append(0x73);
    input.append(0x65);
    input.append(0x74);
    input.append(0x74);
    input.append(0x65);
    input.append(0x72);
    input.append(0x20);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x74);
    input.append(0x68);
    input.append(0x65);
    input.append(0x20);
    input.append(0x31);
    input.append(0x35);
    input.append(0x74);
    input.append(0x68);
    input.append(0x20);
    input.append(0x63);
    input.append(0x65);
    input.append(0x6E);
    input.append(0x74);
    input.append(0x75);
    input.append(0x72);
    input.append(0x79);
    input.append(0x20);
    input.append(0x77);
    input.append(0x68);
    input.append(0x6F);
    input.append(0x20);
    input.append(0x69);
    input.append(0x73);
    input.append(0x20);
    input.append(0x74);
    input.append(0x68);
    input.append(0x6F);
    input.append(0x75);
    input.append(0x67);
    input.append(0x68);
    input.append(0x74);
    input.append(0x20);
    input.append(0x74);
    input.append(0x6F);
    input.append(0x20);
    input.append(0x68);
    input.append(0x61);
    input.append(0x76);
    input.append(0x65);
    input.append(0x20);
    input.append(0x73);
    input.append(0x63);
    input.append(0x72);
    input.append(0x61);
    input.append(0x6D);
    input.append(0x62);
    input.append(0x6C);
    input.append(0x65);
    input.append(0x64);
    input.append(0x20);
    input.append(0x70);
    input.append(0x61);
    input.append(0x72);
    input.append(0x74);
    input.append(0x73);
    input.append(0x20);
    input.append(0x6F);
    input.append(0x66);
    input.append(0x20);
    input.append(0x43);
    input.append(0x69);
    input.append(0x63);
    input.append(0x65);
    input.append(0x72);
    input.append(0x6F);
    input.append(0x27);
    input.append(0x73);
    input.append(0x20);
    input.append(0x44);
    input.append(0x65);
    input.append(0x20);
    input.append(0x46);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x69);
    input.append(0x62);
    input.append(0x75);
    input.append(0x73);
    input.append(0x20);
    input.append(0x42);
    input.append(0x6F);
    input.append(0x6E);
    input.append(0x6F);
    input.append(0x72);
    input.append(0x75);
    input.append(0x6D);
    input.append(0x20);
    input.append(0x65);
    input.append(0x74);
    input.append(0x20);
    input.append(0x4D);
    input.append(0x61);
    input.append(0x6C);
    input.append(0x6F);
    input.append(0x72);
    input.append(0x75);
    input.append(0x6D);
    input.append(0x20);
    input.append(0x66);
    input.append(0x6F);
    input.append(0x72);
    input.append(0x20);
    input.append(0x75);
    input.append(0x73);
    input.append(0x65);
    input.append(0x20);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x61);
    input.append(0x20);
    input.append(0x74);
    input.append(0x79);
    input.append(0x70);
    input.append(0x65);
    input.append(0x20);
    input.append(0x73);
    input.append(0x70);
    input.append(0x65);
    input.append(0x63);
    input.append(0x69);
    input.append(0x6D);
    input.append(0x65);
    input.append(0x6E);
    input.append(0x20);
    input.append(0x62);
    input.append(0x6F);
    input.append(0x6F);
    input.append(0x6B);
    input.append(0x2E);
    input.append(0x20);
    input.append(0x49);
    input.append(0x74);
    input.append(0x20);
    input.append(0x75);
    input.append(0x73);
    input.append(0x75);
    input.append(0x61);
    input.append(0x6C);
    input.append(0x6C);
    input.append(0x79);
    input.append(0x20);
    input.append(0x62);
    input.append(0x65);
    input.append(0x67);
    input.append(0x69);
    input.append(0x6E);
    input.append(0x73);
    input.append(0x20);
    input.append(0x77);
    input.append(0x69);
    input.append(0x74);
    input.append(0x68);

    let result = sha256::sha256(input);

    // result should be 0xD35BF81DDF990122F8B96C7BF88C0737D5080E0C9BC3F7ABF68E6FF0D5F9EA44
    assert(result.len() == 32, 'assertion failed');
    assert(*result[0] == 0xD3, 'assertion failed');
    assert(*result[1] == 0x5B, 'assertion failed');
    assert(*result[2] == 0xF8, 'assertion failed');
    assert(*result[3] == 0x1D, 'assertion failed');
    assert(*result[4] == 0xDF, 'assertion failed');
    assert(*result[5] == 0x99, 'assertion failed');
    assert(*result[6] == 0x01, 'assertion failed');
    assert(*result[7] == 0x22, 'assertion failed');
    assert(*result[8] == 0xF8, 'assertion failed');
    assert(*result[9] == 0xB9, 'assertion failed');
    assert(*result[10] == 0x6C, 'assertion failed');
    assert(*result[11] == 0x7B, 'assertion failed');
    assert(*result[12] == 0xF8, 'assertion failed');
    assert(*result[13] == 0x8C, 'assertion failed');
    assert(*result[14] == 0x07, 'assertion failed');
    assert(*result[15] == 0x37, 'assertion failed');
    assert(*result[16] == 0xD5, 'assertion failed');
    assert(*result[17] == 0x08, 'assertion failed');
    assert(*result[18] == 0x0E, 'assertion failed');
    assert(*result[19] == 0x0C, 'assertion failed');
    assert(*result[20] == 0x9B, 'assertion failed');
    assert(*result[21] == 0xC3, 'assertion failed');
    assert(*result[22] == 0xF7, 'assertion failed');
    assert(*result[23] == 0xAB, 'assertion failed');
    assert(*result[24] == 0xF6, 'assertion failed');
    assert(*result[25] == 0x8E, 'assertion failed');
    assert(*result[26] == 0x6F, 'assertion failed');
    assert(*result[27] == 0xF0, 'assertion failed');
    assert(*result[28] == 0xD5, 'assertion failed');
    assert(*result[29] == 0xF9, 'assertion failed');
    assert(*result[30] == 0xEA, 'assertion failed');
    assert(*result[31] == 0x44, 'assertion failed');
}
#[test]
fn sha256_url() {
    let data = array![
        '{', '"', 't', 'y', 'p', 'e', '"', ':', '"', 'w', 'e', 'b', 'a', 'u', 't', 'h', 'n', '.',
        'g', 'e', 't', '"', ',', '"', 'c', 'h', 'a', 'l', 'l', 'e', 'n', 'g', 'e', '"', ':', '"',
        '3', 'q', '2', '-', '7', '_', '-', 'q', '"', ',', '"', 'o', 'r', 'i', 'g', 'i', 'n', '"',
        ':', '"', 'h', 't', 't', 'p', ':', '/', '/', 'l', 'o', 'c', 'a', 'l', 'h', 'o', 's', 't',
        ':', '5', '1', '7', '3', '"', ',', '"', 'c', 'r', 'o', 's', 's', 'O', 'r', 'i', 'g', 'i',
        'n', '"', ':', 'f', 'a', 'l', 's', 'e', ',', '"', 'o', 't', 'h', 'e', 'r', '_', 'k', 'e',
        'y', 's', '_', 'c', 'a', 'n', '_', 'b', 'e', '_', 'a', 'd', 'd', 'e', 'd', '_', 'h', 'e',
        'r', 'e', '"', ':', '"', 'd', 'o', ' ', 'n', 'o', 't', ' ', 'c', 'o', 'm', 'p', 'a', 'r',
        'e', ' ', 'c', 'l', 'i', 'e', 'n', 't', 'D', 'a', 't', 'a', 'J', 'S', 'O', 'N', ' ', 'a',
        'g', 'a', 'i', 'n', 's', 't', ' ', 'a', ' ', 't', 'e', 'm', 'p', 'l', 'a', 't', 'e', '.',
        ' ', 'S', 'e', 'e', ' ', 'h', 't', 't', 'p', 's', ':', '/', '/', 'g', 'o', 'o', '.', 'g',
        'l', '/', 'y', 'a', 'b', 'P', 'e', 'x', '"', '}',
    ];
    let result = sha256::sha256(data);

    // result should be 0xe5ddd0d703d54d024a1e49cdb614d1f4e9dfa81fff119ca01554ec22d1a45f59
    assert(result.len() == 32, 'assertion failed');
    assert(*result[0] == 0xE5, 'assertion failed');
    assert(*result[1] == 0xDD, 'assertion failed');
    assert(*result[2] == 0xD0, 'assertion failed');
    assert(*result[3] == 0xD7, 'assertion failed');
    assert(*result[4] == 0x03, 'assertion failed');
    assert(*result[5] == 0xD5, 'assertion failed');
    assert(*result[6] == 0x4D, 'assertion failed');
    assert(*result[7] == 0x02, 'assertion failed');
    assert(*result[8] == 0x4A, 'assertion failed');
    assert(*result[9] == 0x1E, 'assertion failed');
    assert(*result[10] == 0x49, 'assertion failed');
    assert(*result[11] == 0xCD, 'assertion failed');
    assert(*result[12] == 0xB6, 'assertion failed');
    assert(*result[13] == 0x14, 'assertion failed');
    assert(*result[14] == 0xD1, 'assertion failed');
    assert(*result[15] == 0xF4, 'assertion failed');
    assert(*result[16] == 0xE9, 'assertion failed');
    assert(*result[17] == 0xDF, 'assertion failed');
    assert(*result[18] == 0xA8, 'assertion failed');
    assert(*result[19] == 0x1F, 'assertion failed');
    assert(*result[20] == 0xFF, 'assertion failed');
    assert(*result[21] == 0x11, 'assertion failed');
    assert(*result[22] == 0x9C, 'assertion failed');
    assert(*result[23] == 0xA0, 'assertion failed');
    assert(*result[24] == 0x15, 'assertion failed');
    assert(*result[25] == 0x54, 'assertion failed');
    assert(*result[26] == 0xEC, 'assertion failed');
    assert(*result[27] == 0x22, 'assertion failed');
    assert(*result[28] == 0xD1, 'assertion failed');
    assert(*result[29] == 0xA4, 'assertion failed');
    assert(*result[30] == 0x5F, 'assertion failed');
    assert(*result[31] == 0x59, 'assertion failed');
}
