[package]
name = "alexandria_json"
version.workspace = true
description = "Starknet json utilities"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/src/json"
edition = "2023_11"
cairo-version = "2.13.1"

[tool]
fmt.workspace = true

[dependencies]
alexandria_math = { path = "../math", version ="0.6.2" }
alexandria_macros = { path = "../macros", version ="0.6.2" }

starknet.workspace = true

[dev-dependencies]
snforge_std.workspace = true