[package]
name = "alexandria_data_structures"
version.workspace = true
description = "A set of Cairo data structure libraries and algorithms"
homepage = "https://github.com/keep-starknet-strange/alexandria/tree/main/packages/data_structures"
edition = "2023_11"
cairo-version = "2.12.1"

[tool]
fmt.workspace = true

[dev-dependencies]
snforge_std.workspace = true
